CREATE TABLE public.contact
(
    id            bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    age           integer NOT NULL,
    first_name    character varying(255) COLLATE pg_catalog."default",
    contact_group character varying(255) COLLATE pg_catalog."default",
    is_favourite  boolean NOT NULL,
    last_name     character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT contact_pkey PRIMARY KEY (id)
);


CREATE TABLE public.address
(
    id          bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address     character varying(255) COLLATE pg_catalog."default",
    city        character varying(255) COLLATE pg_catalog."default",
    country     character varying(255) COLLATE pg_catalog."default",
    index       character varying(255) COLLATE pg_catalog."default",
    is_favorite boolean NOT NULL,
    contact_id  bigint,
    CONSTRAINT address_pkey PRIMARY KEY (id),
    CONSTRAINT fk660ac8r9vntokuyh6agtj8pkh FOREIGN KEY (contact_id)
        REFERENCES public.contact (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


CREATE TABLE public.email
(
    id          bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email       character varying(255) COLLATE pg_catalog."default",
    is_favorite boolean NOT NULL,
    contact_id  bigint,
    CONSTRAINT email_pkey PRIMARY KEY (id),
    CONSTRAINT fk85pasi49am6xyaxoph3i9rvl4 FOREIGN KEY (contact_id)
        REFERENCES public.contact (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public.phone
(
    id               bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    country_code     character varying(255) COLLATE pg_catalog."default",
    is_favorite      boolean NOT NULL,
    telephone_number character varying(255) COLLATE pg_catalog."default",
    contact_id       bigint,
    CONSTRAINT phone_pkey PRIMARY KEY (id),
    CONSTRAINT fkcpsuk117j8h3rplllpvtgs38a FOREIGN KEY (contact_id)
        REFERENCES public.contact (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
